/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dis Equal Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getDisEqualOperator()
 * @model
 * @generated
 */
public interface DisEqualOperator extends RelationOperator
{
} // DisEqualOperator
