/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greater Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getGreaterOperator()
 * @model
 * @generated
 */
public interface GreaterOperator extends RelationOperator
{
} // GreaterOperator
