/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Then Else Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getGuard <em>Guard</em>}</li>
 *   <li>{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getIfBranch <em>If Branch</em>}</li>
 *   <li>{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getElseBranch <em>Else Branch</em>}</li>
 * </ul>
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getIfThenElseExpression()
 * @model
 * @generated
 */
public interface IfThenElseExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guard</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard</em>' containment reference.
   * @see #setGuard(Expression)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getIfThenElseExpression_Guard()
   * @model containment="true"
   * @generated
   */
  Expression getGuard();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getGuard <em>Guard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard</em>' containment reference.
   * @see #getGuard()
   * @generated
   */
  void setGuard(Expression value);

  /**
   * Returns the value of the '<em><b>If Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Branch</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Branch</em>' containment reference.
   * @see #setIfBranch(Expression)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getIfThenElseExpression_IfBranch()
   * @model containment="true"
   * @generated
   */
  Expression getIfBranch();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getIfBranch <em>If Branch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Branch</em>' containment reference.
   * @see #getIfBranch()
   * @generated
   */
  void setIfBranch(Expression value);

  /**
   * Returns the value of the '<em><b>Else Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else Branch</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Branch</em>' containment reference.
   * @see #setElseBranch(Expression)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getIfThenElseExpression_ElseBranch()
   * @model containment="true"
   * @generated
   */
  Expression getElseBranch();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.IfThenElseExpression#getElseBranch <em>Else Branch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Branch</em>' containment reference.
   * @see #getElseBranch()
   * @generated
   */
  void setElseBranch(Expression value);

} // IfThenElseExpression
