/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link quasylab.sibilla.lang.pm.model.NumExpression#getIntPart <em>Int Part</em>}</li>
 *   <li>{@link quasylab.sibilla.lang.pm.model.NumExpression#isIsReal <em>Is Real</em>}</li>
 *   <li>{@link quasylab.sibilla.lang.pm.model.NumExpression#getDecimalPart <em>Decimal Part</em>}</li>
 *   <li>{@link quasylab.sibilla.lang.pm.model.NumExpression#getExponent <em>Exponent</em>}</li>
 * </ul>
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getNumExpression()
 * @model
 * @generated
 */
public interface NumExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Int Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Part</em>' attribute.
   * @see #setIntPart(int)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getNumExpression_IntPart()
   * @model
   * @generated
   */
  int getIntPart();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.NumExpression#getIntPart <em>Int Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Part</em>' attribute.
   * @see #getIntPart()
   * @generated
   */
  void setIntPart(int value);

  /**
   * Returns the value of the '<em><b>Is Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Real</em>' attribute.
   * @see #setIsReal(boolean)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getNumExpression_IsReal()
   * @model
   * @generated
   */
  boolean isIsReal();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.NumExpression#isIsReal <em>Is Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Real</em>' attribute.
   * @see #isIsReal()
   * @generated
   */
  void setIsReal(boolean value);

  /**
   * Returns the value of the '<em><b>Decimal Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decimal Part</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decimal Part</em>' attribute.
   * @see #setDecimalPart(int)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getNumExpression_DecimalPart()
   * @model
   * @generated
   */
  int getDecimalPart();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.NumExpression#getDecimalPart <em>Decimal Part</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decimal Part</em>' attribute.
   * @see #getDecimalPart()
   * @generated
   */
  void setDecimalPart(int value);

  /**
   * Returns the value of the '<em><b>Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exponent</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exponent</em>' attribute.
   * @see #setExponent(int)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getNumExpression_Exponent()
   * @model
   * @generated
   */
  int getExponent();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.NumExpression#getExponent <em>Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exponent</em>' attribute.
   * @see #getExponent()
   * @generated
   */
  void setExponent(int value);

} // NumExpression
