/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sum Diff Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getSumDiffOperator()
 * @model
 * @generated
 */
public interface SumDiffOperator extends EObject
{
} // SumDiffOperator
