/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link quasylab.sibilla.lang.pm.model.System#getPopulation <em>Population</em>}</li>
 * </ul>
 *
 * @see quasylab.sibilla.lang.pm.model.ModelPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends Element
{
  /**
   * Returns the value of the '<em><b>Population</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Population</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Population</em>' containment reference.
   * @see #setPopulation(Population)
   * @see quasylab.sibilla.lang.pm.model.ModelPackage#getSystem_Population()
   * @model containment="true"
   * @generated
   */
  Population getPopulation();

  /**
   * Sets the value of the '{@link quasylab.sibilla.lang.pm.model.System#getPopulation <em>Population</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Population</em>' containment reference.
   * @see #getPopulation()
   * @generated
   */
  void setPopulation(Population value);

} // System
