import matplotlib.pyplot as plt
import pandas

'''
run_data = pandas.read_csv("thread_data10k6k.data", sep=';', index_col=0)
run_data["pool size"].plot()
plt.show()
plt.close()
'''


cached_run_data = pandas.read_csv("run_data_thr_final2.data", sep=';', index_col=0)
cached_thread_data = pandas.read_csv("thread_data_final.data", sep=';', index_col=0).groupby('Concurrent tasks')
fixed_run_data = pandas.read_csv("run_data_fixed_final.data", sep=';', index_col=0)
fixed_thread_data = pandas.read_csv("thread_data_fixed_final.data", sep=';', index_col=0).groupby('Concurrent tasks')
cached_thread_generated_10k6k = pandas.read_csv("thread_data_10k6k_final.data", sep=';', index_col=0).groupby('Concurrent tasks')
cached_thread_generated_10k6k_unlimited = pandas.read_csv("thread_data_unlimited_10k_final.data", sep=';', nrows=1000)
cached_thread_generated_unlimited = pandas.read_csv("thread_data_ulim_final.data", sep=';', nrows=1000)
sequential_run_data = pandas.read_csv("run_data_seq_final.data", sep=";", index_col=0)
multi_run_data = pandas.read_csv("run_data_thr_final2.data", sep=";", index_col=0)
sequential_run_data10k = pandas.read_csv("run_data_seq_final10000.data", sep=";", index_col=0)
multi_run_data10k = pandas.read_csv("run_data_thr_10k6k_final.data", sep=";", index_col=0)
sequential_run_data_desktop = pandas.read_csv("run_data_desktop_seq.data", sep=";", index_col=0)
multi_run_data_desktop = pandas.read_csv("run_data_desktop_thr.data", sep=";", index_col=0)
sequential_run_data_desktop10k = pandas.read_csv("run_data_desktop_seq10000.data", sep=";", index_col=0)
multi_run_data_desktop10k = pandas.read_csv("run_data_desktop_thr_10000.data", sep=";", index_col=0)
run_data_lim = pandas.read_csv("run_data_thr_final2.data", sep=";", index_col=0)
run_data_ulim = pandas.read_csv("run_data_ulim_final.data", sep=";", index_col=0)


ax=cached_run_data.plot()
plot = fixed_run_data.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Cached Thread Pool", "Fixed Thread Pool"])
plt.show()
plt.close()

ax = cached_thread_data['average runtime'].mean().plot()
plot = fixed_thread_data['average runtime'].mean().plot(ax=ax)
plt.gcf().suptitle("Tempo medio d'esecuzione per task")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Cached Thread Pool", "Fixed Thread Pool"])
plt.show()
plt.close()

ax = cached_thread_generated_10k6k["pool size"].mean().plot()
plot = cached_thread_data["pool size"].mean().plot(ax=ax)
plt.gcf().suptitle("Thread generati da Cached Thread Pool con limite")
plot.set_ylabel("Thread")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["10000 task con tempo limite 6000", "1000 task con tempo limite 600"])
plt.show()
plt.close()

ax = cached_thread_generated_10k6k_unlimited["pool size"].plot()
plot = cached_thread_generated_unlimited["pool size"].plot(ax=ax)
plt.gcf().suptitle("Thread generati da Cached Thread Pool senza limite")
plot.set_ylabel("Thread")
plot.legend(["10000 task con tempo limite 6000", "1000 task con tempo limite 600"])
plt.show()
plt.close()

ax=multi_run_data_desktop.plot()
plot = sequential_run_data_desktop.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione su i5 4690 e 1000 task con tempo limite 600")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Multithread Simulation Manager", "Sequential Simulation Manager"])
plt.show()
plt.close()

ax=multi_run_data_desktop10k.plot()
plot = sequential_run_data_desktop10k.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione su i5 4690 e 10000 task con tempo limite 6000")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Multithread Simulation Manager", "Sequential Simulation Manager"])
plt.show()
plt.close()

ax=multi_run_data.plot()
plot = sequential_run_data.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione su A-12 9720P e 1000 task con tempo limite 600")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Multithread Simulation Manager", "Sequential Simulation Manager"])
plt.show()
plt.close()

ax=multi_run_data10k.plot()
plot = sequential_run_data10k.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione su A-12 9720P e 10000 task con tempo limite 6000")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Multithread Simulation Manager", "Sequential Simulation Manager"])
plt.show()
plt.close()

ax=run_data_lim.plot()
plot = run_data_ulim.plot(ax=ax)
plt.gcf().suptitle("Tempo di esecuzione di 1000 task con tempo limite 600")
plot.set_ylabel("Nanosecondi")
plot.set_xlabel("Task in esecuzione concorrente")
plot.legend(["Cached Thread Pool con limite", "Cached Thread Pool senza limite"])
plt.show()
plt.close()
