package quasylab.sibilla.core.simulator.server;

public enum Command {
    CLIENT_DATA, CLIENT_INIT, CLIENT_PING, MASTER_INIT, MASTER_PING, MASTER_TASK, SLAVE_PONG, MASTER_PONG, MONITORING_SUBSCRIBE, MONITORING_UNSUBSCRIBE, MONITORING_UPDATE;
}
