/**
 * generated by Xtext 2.17.0
 */
package quasylab.sibilla.lang.pm;

import quasylab.sibilla.lang.pm.AbstractModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelRuntimeModule extends AbstractModelRuntimeModule {
}
