/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("it.unicam.quasylab.sibilla.java-library-conventions")
}

dependencies {
    api("org.apache.commons:commons-math3:3.0")
}
