/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model.impl;

import org.eclipse.emf.ecore.EClass;

import quasylab.sibilla.lang.pm.model.ModelPackage;
import quasylab.sibilla.lang.pm.model.Species;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Species</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SpeciesImpl extends ElementImpl implements Species
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpeciesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.SPECIES;
  }

} //SpeciesImpl
