/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import quasylab.sibilla.lang.pm.model.ModelPackage;
import quasylab.sibilla.lang.pm.model.SumDiffOperator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sum Diff Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SumDiffOperatorImpl extends MinimalEObjectImpl.Container implements SumDiffOperator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SumDiffOperatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.SUM_DIFF_OPERATOR;
  }

} //SumDiffOperatorImpl
