/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model.impl;

import org.eclipse.emf.ecore.EClass;

import quasylab.sibilla.lang.pm.model.ModelPackage;
import quasylab.sibilla.lang.pm.model.TrueLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>True Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrueLiteralImpl extends ExpressionImpl implements TrueLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrueLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.TRUE_LITERAL;
  }

} //TrueLiteralImpl
