/**
 * generated by Xtext 2.18.0.M3
 */
package quasylab.sibilla.lang.pm.model.impl;

import org.eclipse.emf.ecore.EClass;

import quasylab.sibilla.lang.pm.model.ModelPackage;
import quasylab.sibilla.lang.pm.model.ZeroDivisionOperator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Zero Division Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ZeroDivisionOperatorImpl extends MulDivOperatorImpl implements ZeroDivisionOperator
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ZeroDivisionOperatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelPackage.Literals.ZERO_DIVISION_OPERATOR;
  }

} //ZeroDivisionOperatorImpl
